const KEY = 'alertaSiguraV1';
const defaults = { name:'Alertă Sigură', ip:'198.168.1.10', botMessage:'Salut! Pot să te îndrum către resursele disponibile sau către alerta de panică.', users:[], links:[{title:'WhatsApp',url:'https://www.whatsapp.com/'}], alerts:[] };
let db = JSON.parse(localStorage.getItem(KEY) || 'null') || defaults;
if (!db.ip) { db.ip = defaults.ip; localStorage.setItem(KEY, JSON.stringify(db)); }
const $ = id => document.getElementById(id);
const save = () => { localStorage.setItem(KEY, JSON.stringify(db)); document.title=db.name; };
function applyBrand(){ $('welcomeName').textContent=db.name.toUpperCase(); document.title=db.name; const logo=$('welcomeLogo'); if(db.logo){logo.src=db.logo;logo.classList.remove('hidden')}else logo.classList.add('hidden'); }
const show = id => { ['welcome','clientLogin','clientVerify','adminLogin','adminSetup','clientApp','adminApp'].forEach(x=>$(x).classList.add('hidden')); $(id).classList.remove('hidden'); };
const hash = async value => { const data=new TextEncoder().encode(value); const digest=await crypto.subtle.digest('SHA-256',data); return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join(''); };
document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>show(b.dataset.role==='admin'?'adminLogin':'clientLogin'));
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('welcome'));
document.querySelectorAll('.logout').forEach(b=>b.onclick=()=>show('welcome'));

$('clientEnter').onclick=()=>{ const email=$('clientEmail').value.trim().toLowerCase(), name=$('clientName').value.trim(); if(!email||!name)return $('clientError').textContent='Completează Gmail-ul și numele.'; if(!db.users.includes(email))return $('clientError').textContent='Acest Gmail nu este aprobat încă de administrator.'; sessionStorage.setItem('pendingUser',JSON.stringify({email,name})); $('verifyEmail').textContent=email; $('clientError').textContent=''; show('clientVerify'); };
$('verifyEnter').onclick=()=>{if($('verifyCode').value.trim()!=='123456')return $('verifyError').textContent='Cod incorect. Verifică e-mailul și încearcă din nou.';const user=JSON.parse(sessionStorage.getItem('pendingUser')||'{}');if(!user.email)return show('clientLogin');$('clientGreeting').textContent=user.name;sessionStorage.setItem('user',JSON.stringify(user));sessionStorage.removeItem('pendingUser');$('verifyCode').value='';$('verifyError').textContent='';renderClient();show('clientApp')};
$('adminEnter').onclick=async()=>{ if(!db.adminHash)return show('adminSetup'); if(await hash($('adminCode').value) !== db.adminHash) return $('adminError').textContent='Parolă incorectă.'; $('adminCode').value=''; $('adminError').textContent=''; renderAdmin(); show('adminApp'); };
$('setupAdmin').onclick=async()=>{const p=$('setupPassword').value,c=$('setupPasswordConfirm').value;if(p.length<8)return $('setupError').textContent='Alege cel puțin 8 caractere.';if(p!==c)return $('setupError').textContent='Parolele nu coincid.';db.adminHash=await hash(p);save();$('setupPassword').value=$('setupPasswordConfirm').value='';$('setupError').textContent='';renderAdmin();show('adminApp')};
function renderClient(){ applyBrand(); $('botWelcome').textContent=db.botMessage||defaults.botMessage; $('clientLinks').innerHTML=db.links.map(x=>`<a class="resource-link" href="${esc(x.url)}" target="_blank" rel="noopener">↗ ${esc(x.title)}</a>`).join('') || '<p class="muted">Nu există linkuri încă.</p>'; }
function renderAdmin(){ applyBrand(); $('appName').value=db.name; $('serverIp').value=db.ip; $('botMessage').value=db.botMessage||defaults.botMessage; $('usersList').innerHTML=db.users.length?db.users.map((x,i)=>`<div class="row"><span>${esc(x)}</span><button data-remove-user="${i}">Elimină</button></div>`).join(''):'<p class="muted">Niciun utilizator aprobat.</p>'; $('linksList').innerHTML=db.links.map((x,i)=>`<div class="row"><a href="${esc(x.url)}" target="_blank">${esc(x.title)}</a><button data-remove-link="${i}">Șterge</button></div>`).join(''); const active=db.alerts.filter(x=>!x.resolved); $('alertCount').textContent=`${active.length} noi`; $('alertsList').classList.toggle('empty',!db.alerts.length); $('alertsList').innerHTML=db.alerts.length?db.alerts.map((x,i)=>`<div class="alert-item"><div><b>${esc(x.name)}</b><p class="alert-time">${new Date(x.time).toLocaleString('ro-RO')} · ${x.source}</p>${x.lat?`<a class="map-link" target="_blank" href="https://www.google.com/maps?q=${x.lat},${x.lng}">Deschide locația pe hartă</a>`:'<span class="muted">Locație indisponibilă</span>'}</div>${x.resolved?'<span class="muted">Rezolvată</span>':`<button class="resolve" data-resolve="${i}">Rezolvă</button>`}</div>`).join(''):'Nu există alerte încă.'; document.querySelectorAll('[data-remove-user]').forEach(b=>b.onclick=()=>{db.users.splice(+b.dataset.removeUser,1);save();renderAdmin()}); document.querySelectorAll('[data-remove-link]').forEach(b=>b.onclick=()=>{db.links.splice(+b.dataset.removeLink,1);save();renderAdmin()}); document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>{db.alerts[+b.dataset.resolve].resolved=true;save();renderAdmin()}); }
$('userForm').onsubmit=e=>{e.preventDefault();const email=$('newEmail').value.trim().toLowerCase();if(!db.users.includes(email))db.users.push(email);$('newEmail').value='';save();renderAdmin()};
$('linkForm').onsubmit=e=>{e.preventDefault();db.links.push({title:$('linkTitle').value.trim(),url:$('linkUrl').value.trim()});e.target.reset();save();renderAdmin()};
$('saveSettings').onclick=()=>{db.name=$('appName').value.trim()||defaults.name;db.ip=$('serverIp').value.trim();const file=$('appLogo').files[0];if(!file){save();renderAdmin();return}const reader=new FileReader();reader.onload=()=>{db.logo=reader.result;save();renderAdmin()};reader.readAsDataURL(file)};
$('saveBot').onclick=()=>{db.botMessage=$('botMessage').value.trim()||defaults.botMessage;save();renderAdmin()};
$('changePassword').onclick=async()=>{const p=$('newAdminPassword').value;if(p.length<8)return $('passwordMessage').textContent='Parola trebuie să aibă cel puțin 8 caractere.';db.adminHash=await hash(p);save();$('newAdminPassword').value='';$('passwordMessage').textContent='Parola a fost schimbată.'};
$('panicButton').onclick=()=>{const user=JSON.parse(sessionStorage.getItem('user')||'{}'); if(!confirm('Trimiți acum alerta de ajutor și locația către administrator?'))return; $('panicMessage').textContent='Se obține locația și se trimite alerta…'; const send=(pos)=>{db.alerts.unshift({name:user.name,email:user.email,time:Date.now(),source:'Te ajut cu ceva?',lat:pos?.coords?.latitude,lng:pos?.coords?.longitude,resolved:false});save();$('panicMessage').textContent='Alerta a fost trimisă administratorului.'}; navigator.geolocation?navigator.geolocation.getCurrentPosition(send,()=>send(),{enableHighAccuracy:true,timeout:10000}):send();};
$('botSend').onclick=()=>{const v=$('botInput').value.trim();if(!v)return;const l=$('botLog');l.innerHTML+=`<p><b>Tu:</b> ${esc(v)}</p><p><b>Asistent:</b> Pentru urgențe, apasă SOS. Linkurile aprobate sunt în secțiunea Resurse.</p>`;$('botInput').value='';l.scrollTop=l.scrollHeight};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
applyBrand();
